### ISSUE TITLE
STM32H723+CUBEH7  V1.9.0   Reset the USB Core, ResetBit is not cleared 

### ISSUE THREAD

**Issue by snikeguo** [STMicroelectronics/STM32CubeH7#163] opened 2021-07-06 01:55 UTC
**Describe the set-up**
 * custom board(only  STM32H723ZGT6+USB3300+LM1117-3.3V+Resistor、capacitor )
 *KEIL5

**Describe the bug**
In USB_CoreReset:
Reset the USB Core, ResetBit is not cleared 

before reset:
![image](https://user-images.githubusercontent.com/20830435/124530087-6d6b0180-de3e-11eb-868a-ac5ab9a5ad78.png)
after reset:
![image](https://user-images.githubusercontent.com/20830435/124530837-d43cea80-de3f-11eb-8881-a09622d06c75.png)
datasheet:
![image](https://user-images.githubusercontent.com/20830435/124530850-dbfc8f00-de3f-11eb-94e9-00c4c7c8b05f.png)
![image](https://user-images.githubusercontent.com/20830435/124530870-e61e8d80-de3f-11eb-8291-75d13e41fedc.png)

So I modified the code: 
```
  do
  {
    /*
   if (++count > 200000U)
    {
      return HAL_TIMEOUT;
    }
   */
  } while ((USBx->GRSTCTL & USB_OTG_GRSTCTL_CSRST) == USB_OTG_GRSTCTL_CSRST);
```
But the code stays here ........

CMOD bit is 1 after reset which does not meet expectations .

**How To Reproduce**
1. Please download the IOC file：
[STCubeGenerated.zip](https://github.com/STMicroelectronics/STM32CubeH7/files/6767017/STCubeGenerated.zip)

**Comment by ALABSTM** [comment] 2022-01-30 08:33
Hi @snikeguo, 

Thank you for this report. We will get back to you with a feedback as soon as possible. Please excuse the delay it may take us sometimes to reply. Thank you for your comprehension.

With regards,

**Comment by chengyu666** [comment] 2022-03-04 06:19
I meet the same problem on STM32H743VIT6+USB3343, I've tried almost every method online, but still not work TAT

**Comment by snikeguo** [comment] 2022-03-04 06:32
i used usb3300. pin 0 to gnd.&nbsp; .everything is ok。。。



---Original---
From: ***@***.***&gt;
Date: Fri, Mar 4, 2022 14:20 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [STMicroelectronics/STM32CubeH7] STM32H723+CUBEH7  V1.9.0   Resetthe USB Core, ResetBit is not cleared  (#163)




 
I meet the same problem on STM32H743VIT6+USB3343, I've tried almost every method online, but still not work TAT
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ALABSTM** [comment] 2022-04-05 14:19
Hi @snikeguo,

Thank you again for this detailed report and the proposed workaround.

We recently published **v1.10.0** of the STM32CubeH7 firmware. Have you given it a try to check whether the issue still persists? Indeed, this latest version supports newer versions of the USB Host and Device libraries.

With regards,

**Comment by chengyu666** [comment] 2022-04-06 00:33
this fault may due to hardware error.
in my case, this problem is caused by my usb cable. its DM & DP lines are swapped, so the usb phy can't receive any signal from the host. it takes me 2days to find out the weird problem...

**Comment by ALABSTM** [comment] 2022-04-12 13:36
Hi @snikeguo and @chengyu666,

Thank you for having shared your findings. If I understand correctly, the root-cause of the issue you faced is exclusively at hardware level, mainly your custom board and your cable, not the microcontroller itself.

In this case, please allow me to close this issue. Thank you for having reported and glad to read you overcame these problems.

With regards,

**Closed by ALABSTM** 2022-04-12 13:36 UTC
Labels: bug, invalid, mw, usb
