### ISSUE TITLE
H730 ADC3 Oversampling configuration bug

### ISSUE THREAD

**Issue by KubeckPL** [STMicroelectronics/STM32CubeH7#256] opened 2023-04-19 12:26 UTC
**Caution**
There is an error in the oversampling configuration for the ADC3 in the H730VBT processor in the HAL library.
In the attached screenshots, I have shown the configuration in CubeMX, in the ADC3 handler, and the final values written to the ADC3 registers.
Tools used:
- STM32CubeIDE V1.12,
- HAL Driver version number V1.11.1

**Screenshots**

CubeMX ADC oversampling configuration:
![obraz](https://user-images.githubusercontent.com/51482092/233070281-2a078ce6-af62-404c-90e2-fe8aeef50bc0.png)

MX_ADC3_Init() function:
![obraz](https://user-images.githubusercontent.com/51482092/233071578-817b66dd-d843-435e-ba21-1bfbf094e56b.png)

Final value in CFGR2 register (equal to 4):
![obraz](https://user-images.githubusercontent.com/51482092/233073012-e3c883f4-87ef-4aca-a576-b9c21b613ff0.png)

**Notice**
Oversampling ratios for ADC3 in the H730 MCU are predefined, so CubeMX should only propose predefined values:

![obraz](https://user-images.githubusercontent.com/51482092/233073435-2dfee4d7-bd97-45de-96ad-0090ab3fecef.png)

**Comment by KubeckPL** [comment] 2023-04-19 12:31
The proposed solution in the MX_ADC3_Init() function - using a predefined macro:

![obraz](https://user-images.githubusercontent.com/51482092/233075168-27cc00bc-c3d0-4c43-b6ed-551639211a7f.png)

**Comment by RJMSTM** [comment] 2023-04-20 11:20
Hello @KubeckPL,

Thank you for this report. We will get back to you as soon as we analyze it further. This may take some time. Thank you for your comprehension. 

With regards,
Rania

**Comment by RJMSTM** [comment] 2023-08-07 09:22
Hello @KubeckPL,

Could you please share the code you have used to reproduce the problem?

Regards

**Comment by RJMSTM** [comment] 2024-01-15 09:42
Hello @KubeckPL, 
Any update please, you resolve your problem??

**Comment by KubeckPL** [comment] 2024-01-15 11:16
Hi @RJMSTM.
The bug is still present in the latest version of CubeIDE and CubeMX (V1.14) - I have just checked this.
This problem relates to the code generator built into CubeMX.

![obraz](https://github.com/STMicroelectronics/STM32CubeH7/assets/51482092/74adf072-ba25-418d-a383-8716b22ef930)

**Comment by RJMSTM** [comment] 2024-01-15 13:18
Hello @KubeckPL,

Thank you for this report. The point you reported is actually related to the CubeMX generation problem and not to the firmware published in this repository. Unfortunately, we don't treat aspect related to CubeMX tool in our GitHub repositories. They are rather treated at the [STM32CubeMX](https://community.st.com/s/topic/0TO0X000000BTr8WAG/stm32cubemx) dedicated page of the ST Community .

Since this issue is not directly related to the STM32Cube firmware but rather to our ecosystem, please allow me then to close this thread. Thank you for your comprehension.

With regards,

**Closed** 2024-05-27 16:10 UTC
Labels: bug, cube mx
