### ISSUE TITLE
Invalid compatibility information in README.md of STM32H7xx_HAL_Driver module

### ISSUE THREAD

**Issue by KnoerleMan** [STMicroelectronics/STM32CubeH7#243] opened 2022-11-04 09:26 UTC
The "README.md" file of the "STM32H7xx_HAL_Driver" module contains an invalid compatibility information table.
[Link to invalid README.md](https://github.com/STMicroelectronics/STM32CubeH7/blob/master/Drivers/STM32H7xx_HAL_Driver/README.md#compatibility-information)

It states that the v1.10.0 release of the MCU package is based on the v1.10.2 release of the HAL Driver H7.
Which is **not correct** and can be validated by checking the included "stm32h7xx_hal.c" file which contains the version information.
Anyway there never was a v1.10.2 of the hal drivers...

[The original README of the HAL driver repository therefore lists the correct data](https://github.com/STMicroelectronics/stm32h7xx_hal_driver/blob/master/README.md).

When saying "_It is **crucial** that you use a consistent set of versions for the CMSIS Core - CMSIS Device - HAL, as mentioned in this table._" the given information should be valid.
Please fix this issue asap!

Thanks.

**Comment by ASELSTM** [comment] 2022-11-14 14:04
Hi @KnoerleMan,

Thank you for pointing this out. Indeed, the **v1.10.0** release of the STM32CubeH7 firmware package is based on the **v1.11.0** release of the HAL Driver H7 and not v1.10.2.  The typo has been fixed and it is now available on the [STM32CubeH7](https://github.com/STMicroelectronics/STM32CubeH7) repository as part of this [commit](https://github.com/STMicroelectronics/STM32CubeH7/commit/2262ea8f7687061ee9f06d4054eef15018d0c7fe).

Please allow me thus to close this thread as the issue is fixed now. Thank you for your contribution.

With regards,

**Closed by ASELSTM** 2022-11-14 14:04 UTC
Labels: bug, documentation
