### ISSUE TITLE
DOC and API have a bug in describing STM32H7 ETH->DMACTDRLR (ETH_DMACTXRLR) register

### ISSUE THREAD

**Issue by usaguerrilla** [STMicroelectronics/STM32CubeH7#198] opened 2022-01-14 10:00 UTC
**Caution**
The Issues are strictly limited for the reporting of problem encountered with the software provided in this project.
For any other problem related to the STM32 product, the performance, the hardware characteristics and boards, the tools the environment in general, please post a topic in the [ST Community/STM32 MCUs forum](https://community.st.com/s/group/0F90X000000AXsASAW/stm32-mcus) 

**Describe the set-up**
 * The board (either ST RPN reference or your custom board)
STM32H745ZI
 * IDE or at least the compiler and its version
VISUAL STUDIO

**Describe the bug**

post in the forum about this issue:
https://community.st.com/s/question/0D53W00001JCPy0SAH/eth-transmit-ring-buffer-doesnt-wrap-around-stm32h745zi

```
STM32H745ZI

code comment states:
ETH_DMACTDRLR_TDRL_Msk   /* Transmit Descriptor Ring Length */

documentation states:
TDRL[9:0]: Transmit Descriptor Ring Length
This field sets the maximum number of Tx descriptors in the circular descriptor ring. The
maximum number of descriptors is limited to 1K descriptors. It is recommended to put a
minimum ring descriptor length of 4.

both are wrong. You actually need to write RING_BUFFER_SIZE - 1 (minus one) in order for buffer to work properly.

I set value to 5 and buffer never wraps around when I send 6th item. Then I set it to 4 and it sends 5 items normally and then wraps around on 6th item. so buffer size is 5 but you need to write 4 into the register.
```

**How To Reproduce**
1. Indicate the global behavior of your application project

2. The modules that you suspect to be the cause of the problem (Driver, BSP, MW ...)

3. The use case that generates the problem

4. How we can reproduce the problem

**Additional context**
If you have a first analysis or patch correction, thank you to share your proposal.

**Screenshots**

**Comment by ASELSTM** [comment] 2022-01-27 15:27
Hi @usaguerrilla,

Thank you for your contribution. The point you reported has been already treated at [ST Community](https://community.st.com/s/question/0D53W00001JCPy0SAH/solved-bug-in-docs-eth-transmit-ring-buffer-doesnt-wrap-around-stm32h745zi). An internal bug tracker has been logged and it will be treated by our development team.

As the issue is already treated at the **ST Community**, please allow me then to close this thread to avoid issues duplications.  Thank you for your comprehension.

With regards,

**Closed by ASELSTM** 2022-01-27 15:27 UTC
