### ISSUE TITLE
const-qualify buffers for CRC calculation

### ISSUE THREAD

**Issue by escherstair** [STMicroelectronics/STM32CubeH7#218] opened 2022-05-16 10:58 UTC
One of the best practise in C language is "const-qualify everything".
This brings to more expressive code and gives the compiler more information to optimize the code.

I suggest to const-qualify the buffers used as input for CRC calculation.
I mean `pBuffer` both in the declaration
https://github.com/STMicroelectronics/STM32CubeH7/blob/b340b13929e36a3427b8d94e8b1006022f82273f/Drivers/STM32H7xx_HAL_Driver/Inc/stm32h7xx_hal_crc.h#L311-L312
and in the definition
https://github.com/STMicroelectronics/STM32CubeH7/blob/b340b13929e36a3427b8d94e8b1006022f82273f/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_crc.c#L287
https://github.com/STMicroelectronics/STM32CubeH7/blob/b340b13929e36a3427b8d94e8b1006022f82273f/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_crc.c#L339

**Comment by ASELSTM** [comment] 2022-06-27 19:19
Hi @escherstair,

Thank you for your report. This same issue has also been previously reported by other users  ([link](https://github.com/STMicroelectronics/STM32CubeF4/issues/10)).  This is one of the main points in the tasks queue of our development teams. 

A global update of the HAL and LL drivers is planned. However, this is likely to require some time to be fully deployed on all IPs and all series. The fix implementation and publication is done progressively.  We count on your patience and comprehension.

In order to centralize the issues please allow me to close this one as it is a duplicate of the initial one previously reported . Thank you for your comprehension.

With regards,

**Closed by ASELSTM** 2022-06-27 19:19 UTC
Labels: hal
