### ISSUE TITLE
USART fails to compile

### ISSUE THREAD

**Issue by fnadeau** [STMicroelectronics/STM32CubeH7#43] opened 2020-06-12 00:31 UTC
**Caution**
The Issues are strictly limited for the reporting of problem encountered with the software provided in this project.
For any other problem related to the STM32 product, the performance, the hardware characteristics and boards, the tools the environment in general, please post a topic in the [ST Community/STM32 MCUs forum](https://community.st.com/s/group/0F90X000000AXsASAW/stm32-mcus) 

**Describe the set-up**
 * Custom board with STM32H743
 * STM32CubeIDE 1.3.0
 * STM32CubeMX 5.6.1

**Describe the bug**
Compiling stm32h7xx_hal_usart.c fails

**How To Reproduce**
1. Indicate the global behavior of your application project
Use USART1 as Synchronous master

2. The modules that you suspect to be the cause of the problem (Driver, BSP, MW ...)
USART1

3. The use case that generates the problem
Compiling

4. How we can reproduce the problem
STM32CubeMX 5.6.1
- Start new project fot STM32H743VITx
- From Connectivity, add USART1 as Synchronus master
- In Project Manager, give name, select STM32CubeIDE
- Firmware package is STM32Cube FW_H7 V1.7.0
- Generate code
STM32CubeIDE 1.3.0
- Build project
Gives:
../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_usart.c: In function 'HAL_USART_IRQHandler':
../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_usart.c:2153:7: warning: implicit declaration of function '__HAL_UART_CLEAR_FLAG'; did you mean '__HAL_USART_CLEAR_FLAG'? [-Wimplicit-function-declaration]
       __HAL_UART_CLEAR_FLAG(husart, UART_CLEAR_RTOF);
       ^~~~~~~~~~~~~~~~~~~~~
       __HAL_USART_CLEAR_FLAG
../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_usart.c:2153:37: error: 'UART_CLEAR_RTOF' undeclared (first use in this function); did you mean 'USART_CLEAR_RTOF'?
       __HAL_UART_CLEAR_FLAG(husart, UART_CLEAR_RTOF);
                                     ^~~~~~~~~~~~~~~
                                     USART_CLEAR_RTOF

**Additional context**
Pull-request will follow, it seems to be just a typo.

**Screenshots**
None

**Comment by ASELSTM** [comment] 2020-06-12 16:34
Hi @fnadeau,

Thank you for your contribution.

Actually, we are already aware of this issue and have fixed it internally. However, the fix has not been published yet. It is scheduled for next release.

Since the issue is already fixed and planned for the next release, please allow me to close this issue. Thank you for your comprehension.

Best regards,

**Closed by ASELSTM** 2020-06-12 16:34 UTC
