### ISSUE TITLE
Error comment in "system_stm32h7xx. c" file

### ISSUE THREAD

**Issue by chenjingyuanku** [STMicroelectronics/STM32CubeH7#246] opened 2022-11-25 01:22 UTC
The comment near the macro definition of "**VECT_TAB_BASE_ADDRESS**" in the "**system_stm32h7xx. c**" file says "**This value must be a multiple of 0x300.**" It should actually be **0x200**, which is a very misleading comment.

**Comment by carlo-dev-git** [comment] 2022-12-10 18:26
@ALABSTM I think this is duplicate of https://github.com/STMicroelectronics/cmsis_device_h7/issues/2
and it was fixed in release V1.11.0

**Comment by TOUNSTM** [comment] 2023-02-23 17:26
Hello,

Thank you for your report, but as @carlo-dev-git said  This issue has been previously reported by other users and it was fixed.
Please allow me to close this issue. Thank you again for your comprehension and for your contribution.

Best Regards

**Closed** 2023-02-23 17:27 UTC
Labels: duplicate, cmsis
